// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTa8eCq_NnvrAAFZNt1istrukatMxFfLo',
    appId: '1:270224099710:web:683afbc1de803c909f0b2f',
    messagingSenderId: '270224099710',
    projectId: 'nagleh-app',
    authDomain: 'nagleh-app.firebaseapp.com',
    storageBucket: 'nagleh-app.appspot.com',
    measurementId: 'G-EFDBW3WH9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYygdMFpA_JIFyjrUPzoTT0TA2vATARg',
    appId: '1:270224099710:android:d45ae1632915b41a9f0b2f',
    messagingSenderId: '270224099710',
    projectId: 'nagleh-app',
    storageBucket: 'nagleh-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhUk3qptWPZVqatIis-5hiHcBUk9ccYc',
    appId: '1:270224099710:ios:a1d05eb27e2638839f0b2f',
    messagingSenderId: '270224099710',
    projectId: 'nagleh-app',
    storageBucket: 'nagleh-app.appspot.com',
    iosClientId: '270224099710-3pc50kbaqjh6lsulomgphmo1ot2aupre.apps.googleusercontent.com',
    iosBundleId: 'com.example.EShop.eShop',
  );
}
